# -*- coding: utf-8 -*-
"""LandslideDatingApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-VCNR3CJ2QysPaaUK8s-uQatJdbmhZ_
"""

import ee
import geemap.foliumap as geemap
import ipywidgets as widgets
from IPython.display import display
import os
import ee
import geemap.foliumap as geemap
import streamlit as st
from shapely.geometry import Polygon
geemap.ee_initialize()
Map = geemap.Map(center=[61.5, 100], zoom=18)
Map.add_basemap('OpenRailwayMap')
Map.to_streamlit(height=300)
Map
