# -*- coding: utf-8 -*-
"""LandslideDatingApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-VCNR3CJ2QysPaaUK8s-uQatJdbmhZ_
"""

import ee
import geemap.foliumap as geemap
import ipywidgets as widgets
from IPython.display import display
import os
import ee
import geemap.foliumap as geemap
import streamlit as st
from shapely.geometry import Polygon
# 创建地图
# ———— 2. 创建地图对象 ————
m = geemap.Map(
    basemap="HYBRID",
    plugin_Draw=False,
    locate_control=False,
    add_google_map=False
)
m.set_center(-98.5795, 39.8283, 4)

# ———— 3. Streamlit 布局 ————
st.title("美国县级行政区划可视化")

# 侧边栏中的按钮
if st.sidebar.button("添加县级行政区划"):
    # 加载 EE 数据集
    counties = ee.FeatureCollection("TIGER/2018/Counties")
    # 可视化参数
    vis = {
        "color": "FF5500",
        "width": 1,
        "fillColor": "00000000",
    }
    m.add_layer(counties.style(**vis), {}, "美国县级行政区划")
    # 添加图例
    m.add_legend(
        title="县界边界",
        colors=["#FF5500"],
        labels=["County Boundaries"],
    )
    st.sidebar.success("县级行政区划已添加！")

# ———— 4. 渲染地图 ————
st.subheader("地图视图")
m.to_streamlit(height=600)
